"""
relative_atomic_weight - http://www.chem.qmul.ac.uk/iupac/AtWt/ (2013)
atomic polarizability - http://ctcp.massey.ac.nz/Tablepol2014.pdf (2014/12/22) 

"""

periodic_table = {
    '*':{
    'symbol':'*',
    'name':'Any Atom',
    'relative_atomic_weight':0,
    'isotopes': [],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': None,
    'atomic_polarizability': None,
    },
    1:{
    'symbol':'H',
    'name':'Hydrogen',
    'relative_atomic_weight':1.008,
    'isotopes': [],
    'vdw_radius': 1.1,
    'pauling_electronegativity': 2.20,
    'ar_electronegativity': 2.20,
    'atomic_polarizability': 4.5,
    },
    2:{
    'symbol':'He',
    'name':'Helium',
    'relative_atomic_weight':4.002602,
    'isotopes': [],
    'vdw_radius': 1.4,
    'pauling_electronegativity': None,
    'ar_electronegativity': None,
    'atomic_polarizability': 1.383,
    },
    3:{
    'symbol':'Li',
    'name':'Lithium',
    'relative_atomic_weight':6.94,
    'isotopes': [],
    'vdw_radius': 1.82,
    'pauling_electronegativity': 0.98,
    'ar_electronegativity': 0.97,
    'atomic_polarizability': 164.05,
    },
    4:{
    'symbol':'Be',
    'name':'Beryllium',
    'relative_atomic_weight':9.0121831,
    'isotopes': [],
    'vdw_radius': 1.53,
    'pauling_electronegativity': 1.57,
    'ar_electronegativity': 1.47,
    'atomic_polarizability': 37.775,
    },
    5:{
    'symbol':'B',
    'name':'Boron',
    'relative_atomic_weight':10.81,
    'isotopes': [],
    'vdw_radius': 1.92,
    'pauling_electronegativity': 2.04,
    'ar_electronegativity': 2.01,
    'atomic_polarizability': 20.5,
    },
    6:{
    'symbol':'C',
    'name':'Carbon',
    'relative_atomic_weight':12.011,
    'isotopes': [],
    'vdw_radius': 1.7,
    'pauling_electronegativity': 2.55,
    'ar_electronegativity': 2.50,
    'atomic_polarizability': 11.0,
    },
    7:{
    'symbol':'N',
    'name':'Nitrogen',
    'relative_atomic_weight':14.007,
    'isotopes': [],
    'vdw_radius': 1.55,
    'pauling_electronegativity': 3.04,
    'ar_electronegativity': 3.07,
    'atomic_polarizability': 7.43,
    },
    8:{
    'symbol':'O',
    'name':'Oxygen',
    'relative_atomic_weight':15.999,
    'isotopes': [],
    'vdw_radius': 1.52,
    'pauling_electronegativity': 3.44,
    'ar_electronegativity': 3.50,
    'atomic_polarizability': 6.04,
    },
    9:{
    'symbol':'F',
    'name':'Fluorine',
    'relative_atomic_weight':18.998403163,
    'isotopes': [],
    'vdw_radius': 1.47,
    'pauling_electronegativity': 3.98,
    'ar_electronegativity': 4.10,
    'atomic_polarizability': 3.76,
    },
    10:{
    'symbol':'Ne',
    'name':'Neon',
    'relative_atomic_weight':20.1797,
    'isotopes': [],
    'vdw_radius': 1.54,
    'pauling_electronegativity': None,
    'ar_electronegativity': None,
    'atomic_polarizability': 2.68,
    },
    11:{
    'symbol':'Na',
    'name':'Sodium',
    'relative_atomic_weight':22.98976928,
    'isotopes': [],
    'vdw_radius': 2.27,
    'pauling_electronegativity': 0.93,
    'ar_electronegativity': 1.01,
    'atomic_polarizability': 162.6,
    },
    12:{
    'symbol':'Mg',
    'name':'Magnesium',
    'relative_atomic_weight':24.305,
    'isotopes': [],
    'vdw_radius': 1.73,
    'pauling_electronegativity': 1.31,
    'ar_electronegativity': 1.23,
    'atomic_polarizability': 71.7,
    },
    13:{
    'symbol':'Al',
    'name':'Aluminium',
    'relative_atomic_weight':26.9815385,
    'isotopes': [],
    'vdw_radius': 1.84,
    'pauling_electronegativity': 1.61,
    'ar_electronegativity': 1.47,
    'atomic_polarizability': 56.3,
    },
    14:{
    'symbol':'Si',
    'name':'Silicon',
    'relative_atomic_weight':28.085,
    'isotopes': [],
    'vdw_radius': 2.10,
    'pauling_electronegativity': 1.90,
    'ar_electronegativity': 1.74,
    'atomic_polarizability': 36.7,
    },
    15:{
    'symbol':'P',
    'name':'Phosphorus',
    'relative_atomic_weight':30.973761998,
    'isotopes': [],
    'vdw_radius': 1.80,
    'pauling_electronegativity': 2.19,
    'ar_electronegativity': 2.06,
    'atomic_polarizability': 24.7,
    },
    16:{
    'symbol':'S',
    'name':'Sulfur',
    'relative_atomic_weight':32.06,
    'isotopes': [],
    'vdw_radius': 1.80,
    'pauling_electronegativity': 2.58,
    'ar_electronegativity': 2.44,
    'atomic_polarizability': 19.6,
    },
    17:{
    'symbol':'Cl',
    'name':'Chlorine',
    'relative_atomic_weight':35.45,
    'isotopes': [],
    'vdw_radius': 1.75,
    'pauling_electronegativity': 3.16,
    'ar_electronegativity': 2.83,
    'atomic_polarizability': 14.7,
    },
    18:{
    'symbol':'Ar',
    'name':'Argon',
    'relative_atomic_weight':39.948,
    'isotopes': [],
    'vdw_radius': 1.88,
    'pauling_electronegativity': None,
    'ar_electronegativity': None,
    'atomic_polarizability': 11.10,
    },
    19:{
    'symbol':'K',
    'name':'Potassium',
    'relative_atomic_weight':39.0983,
    'isotopes': [],
    'vdw_radius': 2.71,
    'pauling_electronegativity': 0.82,
    'ar_electronegativity': 0.91,
    'atomic_polarizability': 298.1,
    },
    20:{
    'symbol':'Ca',
    'name':'Calcium',
    'relative_atomic_weight':40.078,
    'isotopes': [],
    'vdw_radius': 2.31,
    'pauling_electronegativity': 1.0,
    'ar_electronegativity': 1.04,
    'atomic_polarizability': 160,
    },
    21:{
    'symbol':'Sc',
    'name':'Scandium',
    'relative_atomic_weight':44.955908,
    'isotopes': [],
    'vdw_radius': 2.11,
    'pauling_electronegativity': 1.36,
    'ar_electronegativity': 1.20,
    'atomic_polarizability': 120,
    },
    22:{
    'symbol':'Ti',
    'name':'Titanium',
    'relative_atomic_weight':47.867,
    'isotopes': [],
    'vdw_radius': 2.15,
    'pauling_electronegativity': 1.54,
    'ar_electronegativity': 1.32,
    'atomic_polarizability': 99,
    },
    23:{
    'symbol':'V',
    'name':'Vanadium',
    'relative_atomic_weight':50.9415,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.63,
    'ar_electronegativity': 1.45,
    'atomic_polarizability': 84,
    },
    24:{
    'symbol':'Cr',
    'name':'Chromium',
    'relative_atomic_weight':51.9961,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.66,
    'ar_electronegativity': 1.56,
    'atomic_polarizability': 78,
    },
    25:{
    'symbol':'Mn',
    'name':'Manganese',
    'relative_atomic_weight':54.938044,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.55,
    'ar_electronegativity': 1.60,
    'atomic_polarizability': 63,
    },
    26:{
    'symbol':'Fe',
    'name':'Iron',
    'relative_atomic_weight':55.845,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.83,
    'ar_electronegativity': 1.64,
    'atomic_polarizability': 57,
    },
    27:{
    'symbol':'Co',
    'name':'Cobalt',
    'relative_atomic_weight':58.933194,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 1.88,
    'ar_electronegativity': 1.70,
    'atomic_polarizability': 51,
    },
    28:{
    'symbol':'Ni',
    'name':'Nickel',
    'relative_atomic_weight':58.6934,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 1.91,
    'ar_electronegativity': 1.75,
    'atomic_polarizability': 46,
    },
    29:{
    'symbol':'Cu',
    'name':'Copper',
    'relative_atomic_weight':63.546,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 1.90,
    'ar_electronegativity': 1.75,
    'atomic_polarizability': 53.44,
    },
    30:{
    'symbol':'Zn',
    'name':'Zinc',
    'relative_atomic_weight':65.38,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 1.65,
    'ar_electronegativity': 1.66,
    'atomic_polarizability': 39.2,
    },
    31:{
    'symbol':'Ga',
    'name':'Gallium',
    'relative_atomic_weight':69.723,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 1.81,
    'ar_electronegativity': 1.82,
    'atomic_polarizability': 54.9,
    },
    32:{
    'symbol':'Ge',
    'name':'Germanium',
    'relative_atomic_weight':72.630,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.01,
    'ar_electronegativity': 2.02,
    'atomic_polarizability': 41.0,
    },
    33:{
    'symbol':'As',
    'name':'Arsenic',
    'relative_atomic_weight':74.921595,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 2.18,
    'ar_electronegativity': 2.20,
    'atomic_polarizability': 29.1,
    },
    34:{
    'symbol':'Se',
    'name':'Selenium',
    'relative_atomic_weight':78.971,
    'isotopes': [],
    'vdw_radius': 1.9,
    'pauling_electronegativity': 2.55,
    'ar_electronegativity': 2.48,
    'atomic_polarizability': 26.24,
    },
    35:{
    'symbol':'Br',
    'name':'Bromine',
    'relative_atomic_weight':79.904,
    'isotopes': [],
    'vdw_radius': 1.9,
    'pauling_electronegativity': 2.96,
    'ar_electronegativity': 2.74,
    'atomic_polarizability': 21.9,
    },
    36:{
    'symbol':'Kr',
    'name':'Krypton',
    'relative_atomic_weight':83.798,
    'isotopes': [],
    'vdw_radius': 2.02,
    'pauling_electronegativity': 3.0,
    'ar_electronegativity': 2.94,
    'atomic_polarizability': 16.8,
    },
    37:{
    'symbol':'Rb',
    'name':'Rubidium',
    'relative_atomic_weight':85.4678,
    'isotopes': [],
    'vdw_radius': 2.9,
    'pauling_electronegativity': 0.82,
    'ar_electronegativity': 0.89,
    'atomic_polarizability': 318.6,
    },
    38:{
    'symbol':'Sr',
    'name':'Strontium',
    'relative_atomic_weight':87.62,
    'isotopes': [],
    'vdw_radius': 2.55,
    'pauling_electronegativity': 0.95,
    'ar_electronegativity': 0.99,
    'atomic_polarizability': 199,
    },
    39:{
    'symbol':'Y',
    'name':'Yttrium',
    'relative_atomic_weight':88.90584,
    'isotopes': [],
    'vdw_radius': 2.4,
    'pauling_electronegativity': 1.22,
    'ar_electronegativity': 1.11,
    'atomic_polarizability': 153,
    },
    40:{
    'symbol':'Zr',
    'name':'Zirconium',
    'relative_atomic_weight':91.224,
    'isotopes': [],
    'vdw_radius': 2.3,
    'pauling_electronegativity': 1.33,
    'ar_electronegativity': 1.22,
    'atomic_polarizability': 121,
    },
    41:{
    'symbol':'Nb',
    'name':'Niobium',
    'relative_atomic_weight':92.90637,
    'isotopes': [],
    'vdw_radius': 2.15,
    'pauling_electronegativity': 1.6,
    'ar_electronegativity': 1.23,
    'atomic_polarizability': 106,
    },
    42:{
    'symbol':'Mo',
    'name':'Molybdenum',
    'relative_atomic_weight':95.95,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.16,
    'ar_electronegativity': 1.30,
    'atomic_polarizability': 86,
    },
    43:{
    'symbol':'Tc',
    'name':'Technetium',
    'relative_atomic_weight':97,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.9,
    'ar_electronegativity': 1.36,
    'atomic_polarizability': 77,
    },
    44:{
    'symbol':'Ru',
    'name':'Ruthenium',
    'relative_atomic_weight':101.07,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 2.2,
    'ar_electronegativity': 1.42,
    'atomic_polarizability': 65,
    },
    45:{
    'symbol':'Rh',
    'name':'Rhodium',
    'relative_atomic_weight':102.90550,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 2.28,
    'ar_electronegativity': 1.45,
    'atomic_polarizability': 58,
    },
    46:{
    'symbol':'Pd',
    'name':'Palladium',
    'relative_atomic_weight':106.42,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 2.2,
    'ar_electronegativity': 1.35,
    'atomic_polarizability': 32,
    },
    47:{
    'symbol':'Ag',
    'name':'Silver',
    'relative_atomic_weight':107.8682,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 1.93,
    'ar_electronegativity': 1.42,
    'atomic_polarizability': 52.2,
    },
    48:{
    'symbol':'Cd',
    'name':'Cadmium',
    'relative_atomic_weight':112.414,
    'isotopes': [],
    'vdw_radius': 2.2,
    'pauling_electronegativity': 1.69,
    'ar_electronegativity': 1.46,
    'atomic_polarizability': 46.3,
    },
    49:{
    'symbol':'In',
    'name':'Indium',
    'relative_atomic_weight':114.818,
    'isotopes': [],
    'vdw_radius': 2.2,
    'pauling_electronegativity': 1.78,
    'ar_electronegativity': 1.49,
    'atomic_polarizability': 65.2,
    },
    50:{
    'symbol':'Sn',
    'name':'Tin',
    'relative_atomic_weight':118.710,
    'isotopes': [],
    'vdw_radius': 2.25,
    'pauling_electronegativity': 1.96,
    'ar_electronegativity': 1.72,
    'atomic_polarizability': 52,
    },
    51:{
    'symbol':'Sb',
    'name':'Antimony',
    'relative_atomic_weight':121.760,
    'isotopes': [],
    'vdw_radius': 2.2,
    'pauling_electronegativity': 2.05,
    'ar_electronegativity': 1.82,
    'atomic_polarizability': 45,
    },
    52:{
    'symbol':'Te',
    'name':'Tellurium',
    'relative_atomic_weight':127.60,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.1,
    'ar_electronegativity': 2.01,
    'atomic_polarizability': 37,
    },
    53:{
    'symbol':'I',
    'name':'Iodine',
    'relative_atomic_weight':126.90447,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.66,
    'ar_electronegativity': 2.21,
    'atomic_polarizability': 35.1,
    },
    54:{
    'symbol':'Xe',
    'name':'Xenon',
    'relative_atomic_weight':131.293,
    'isotopes': [],
    'vdw_radius': 2.16,
    'pauling_electronegativity': 2.6,
    'ar_electronegativity': 2.40,
    'atomic_polarizability': 27.06,
    },
    55:{
    'symbol':'Cs',
    'name':'Caesium',
    'relative_atomic_weight':132.90545196,
    'isotopes': [],
    'vdw_radius': 3.0,
    'pauling_electronegativity': 0.79,
    'ar_electronegativity': 0.86,
    'atomic_polarizability': 399,
    },
    56:{
    'symbol':'Ba',
    'name':'Barium',
    'relative_atomic_weight':137.327,
    'isotopes': [],
    'vdw_radius': 2.7,
    'pauling_electronegativity': 0.89,
    'ar_electronegativity': 0.97,
    'atomic_polarizability': 262.2,
    },
    57:{
    'symbol':'La',
    'name':'Lanthanum',
    'relative_atomic_weight':138.90547,
    'isotopes': [],
    'vdw_radius': 2.5,
    'pauling_electronegativity': 1.10,
    'ar_electronegativity': 1.08,
    'atomic_polarizability': 210,
    },
    58:{
    'symbol':'Ce',
    'name':'Cerium',
    'relative_atomic_weight':140.116,
    'isotopes': [],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.12,
    'ar_electronegativity': 1.08,
    'atomic_polarizability': 200,
    },
    59:{
    'symbol':'Pr',
    'name':'Praseodymium',
    'relative_atomic_weight':140.90766,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.13,
    'ar_electronegativity': 1.07,
    'atomic_polarizability': 190,
    },
    60:{
    'symbol':'Nd',
    'name':'Neodymium',
    'relative_atomic_weight':144.242,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.14,
    'ar_electronegativity': 1.07,
    'atomic_polarizability': 212,
    },
    61:{
    'symbol':'Pm',
    'name':'Promethium',
    'relative_atomic_weight':145,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': 1.07,
    'atomic_polarizability': 203,
    },
    62:{
    'symbol':'Sm',
    'name':'Samarium',
    'relative_atomic_weight':150.36,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.17,
    'ar_electronegativity': 1.07,
    'atomic_polarizability': 194,
    },
    63:{
    'symbol':'Eu',
    'name':'Europium',
    'relative_atomic_weight':151.964,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': 1.01,
    'atomic_polarizability': 187,
    },
    64:{
    'symbol':'Gd',
    'name':'Gadolinium',
    'relative_atomic_weight':157.25,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.20,
    'ar_electronegativity': 1.11,
    'atomic_polarizability': 159,
    },
    65:{
    'symbol':'Tb',
    'name':'Terbium',
    'relative_atomic_weight':158.92535,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': 1.10,
    'atomic_polarizability': 172,
    },
    66:{
    'symbol':'Dy',
    'name':'Dysprosium',
    'relative_atomic_weight':162.500,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.22,
    'ar_electronegativity': 1.10,
    'atomic_polarizability': 165,
    },
    67:{
    'symbol':'Ho',
    'name':'Holmium',
    'relative_atomic_weight':164.93033,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.23,
    'ar_electronegativity': 1.10,
    'atomic_polarizability': 159,
    },
    68:{
    'symbol':'Er',
    'name':'Erbium',
    'relative_atomic_weight':167.259,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.24,
    'ar_electronegativity': 1.11,
    'atomic_polarizability': 153,
    },
    69:{
    'symbol':'Tm',
    'name':'Thulium',
    'relative_atomic_weight':168.93422,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.25,
    'ar_electronegativity': 1.11,
    'atomic_polarizability': 147,
    },
    70:{
    'symbol':'Yb',
    'name':'Ytterbium',
    'relative_atomic_weight':173.054,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': 1.06,
    'atomic_polarizability': 142,
    },
    71:{
    'symbol':'Lu',
    'name':'Lutetium',
    'relative_atomic_weight':174.9668,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.27,
    'ar_electronegativity': 1.14,
    'atomic_polarizability': 148,
    },
    72:{
    'symbol':'Hf',
    'name':'Hafnium',
    'relative_atomic_weight':178.49,
    'isotopes': [],
    'vdw_radius': 2.25,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.23,
    'atomic_polarizability': 109,
    },
    73:{
    'symbol':'Ta',
    'name':'Tantalum',
    'relative_atomic_weight':180.94788,
    'isotopes': [],
    'vdw_radius': 2.2,
    'pauling_electronegativity': 1.5,
    'ar_electronegativity': 1.33,
    'atomic_polarizability': 88,
    },
    74:{
    'symbol':'W',
    'name':'Tungsten',
    'relative_atomic_weight':183.84,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.36,
    'ar_electronegativity': 1.40,
    'atomic_polarizability': 75,
    },
    75:{
    'symbol':'Re',
    'name':'Rhenium',
    'relative_atomic_weight':186.207,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 1.9,
    'ar_electronegativity': 1.46,
    'atomic_polarizability': 65,
    },
    76:{
    'symbol':'Os',
    'name':'Osmium',
    'relative_atomic_weight':190.23,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 2.2,
    'ar_electronegativity': 1.52,
    'atomic_polarizability': 57,
    },
    77:{
    'symbol':'Ir',
    'name':'Iridium',
    'relative_atomic_weight':192.217,
    'isotopes': [],
    'vdw_radius': 2.0,
    'pauling_electronegativity': 2.2,
    'ar_electronegativity': 1.55,
    'atomic_polarizability': 51,
    },
    78:{
    'symbol':'Pt',
    'name':'Platinum',
    'relative_atomic_weight':195.084,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 2.28,
    'ar_electronegativity': 1.44,
    'atomic_polarizability': 44,
    },
    79:{
    'symbol':'Au',
    'name':'Gold',
    'relative_atomic_weight':196.966569,
    'isotopes': [],
    'vdw_radius': 2.1,
    'pauling_electronegativity': 2.54,
    'ar_electronegativity': 1.42,
    'atomic_polarizability': 35.1,
    },
    80:{
    'symbol':'Hg',
    'name':'Mercury',
    'relative_atomic_weight':200.592,
    'isotopes': [],
    'vdw_radius': 2.05,
    'pauling_electronegativity': 2.0,
    'ar_electronegativity': 1.44,
    'atomic_polarizability': 34.4,
    },
    81:{
    'symbol':'Tl',
    'name':'Thallium',
    'relative_atomic_weight':204.38,
    'isotopes': [],
    'vdw_radius': 2.2,
    'pauling_electronegativity': 1.62,
    'ar_electronegativity': 1.44,
    'atomic_polarizability': 70.0,
    },
    82:{
    'symbol':'Pb',
    'name':'Lead',
    'relative_atomic_weight':207.2,
    'isotopes': [],
    'vdw_radius': 2.3,
    'pauling_electronegativity': 2.33,
    'ar_electronegativity': 1.55,
    'atomic_polarizability': 46,
    },
    83:{
    'symbol':'Bi',
    'name':'Bismuth',
    'relative_atomic_weight':208.98040,
    'isotopes': [],
    'vdw_radius': 2.3,
    'pauling_electronegativity': 2.02,
    'ar_electronegativity': 1.67,
    'atomic_polarizability': 50,
    },
    84:{
    'symbol':'Po',
    'name':'Polonium',
    'relative_atomic_weight':209,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 2.0,
    'ar_electronegativity': 1.76,
    'atomic_polarizability': 46,
    },
    85:{
    'symbol':'At',
    'name':'Astatine',
    'relative_atomic_weight':210,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 2.2,
    'ar_electronegativity': 1.90,
    'atomic_polarizability': 45.6,
    },
    86:{
    'symbol':'Rn',
    'name':'Radon',
    'relative_atomic_weight':222,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': None,
    'ar_electronegativity': 2.06,
    'atomic_polarizability': 33.18,
    },
    87:{
    'symbol':'Fr',
    'name':'Francium',
    'relative_atomic_weight':223,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 0.7,
    'ar_electronegativity': 0.86,
    'atomic_polarizability': 317.8,
    },
    88:{
    'symbol':'Ra',
    'name':'Radium',
    'relative_atomic_weight':226,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 0.9,
    'ar_electronegativity': 0.97,
    'atomic_polarizability': 246.2,
    },
    89:{
    'symbol':'Ac',
    'name':'Actinium',
    'relative_atomic_weight':227,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.1,
    'ar_electronegativity': 1.0,
    'atomic_polarizability': 217,
    },
    90:{
    'symbol':'Th',
    'name':'Thorium',
    'relative_atomic_weight':232.0377,
    'isotopes': [],
    'vdw_radius': 2.4,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.11,
    'atomic_polarizability': 217,
    },
    91:{
    'symbol':'Pa',
    'name':'Protactinium',
    'relative_atomic_weight':231.03588,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.5,
    'ar_electronegativity': 1.14,
    'atomic_polarizability': 171,
    },
    92:{
    'symbol':'U',
    'name':'Uranium',
    'relative_atomic_weight':238.02891,
    'isotopes': [],
    'vdw_radius': 2.3,
    'pauling_electronegativity': 1.38,
    'ar_electronegativity': 1.22,
    'atomic_polarizability': 152.7,
    },
    93:{
    'symbol':'Np',
    'name':'Neptunium',
    'relative_atomic_weight':237,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.36,
    'ar_electronegativity': 1.22,
    'atomic_polarizability': 167,
    },
    94:{
    'symbol':'Pu',
    'name':'Plutonium',
    'relative_atomic_weight':244,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.28,
    'ar_electronegativity': 1.22,
    'atomic_polarizability': 165,
    },
    95:{
    'symbol':'Am',
    'name':'Americium',
    'relative_atomic_weight':243,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 157,
    },
    96:{
    'symbol':'Cm',
    'name':'Curium',
    'relative_atomic_weight':247,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 155,
    },
    97:{
    'symbol':'Bk',
    'name':'Berkelium',
    'relative_atomic_weight':247,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 153,
    },
    98:{
    'symbol':'Cf',
    'name':'Californium',
    'relative_atomic_weight':251,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 138,
    },
    99:{
    'symbol':'En',
    'name':'Einsteinium',
    'relative_atomic_weight':252,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 133,
    },
    100:{
    'symbol':'Fm',
    'name':'Fermium',
    'relative_atomic_weight':257,
    'isotopes':[],
    'vdw_radius': 0,
    'pauling_electronegativity': 1.3,
    'ar_electronegativity': 1.2,
    'atomic_polarizability': 161,
    }
}

periodic_table_by_symbol = {v['symbol']:{'z':k,
                            'relative_atomic_weight':v['relative_atomic_weight'],
                            'name':v['name'],
                            'isotopes':v['isotopes']} for k,v in periodic_table.iteritems()}